version: "{build}"

branches:
  except:
    - '/^dependabot\/.*/'

image:
  - Visual Studio 2015
environment:
  matrix:
    - nodejs_version: "14"
    - nodejs_version: "16"
    - nodejs_version: "18"

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install
  - npm install msnodesqlv8@^2

platform:
  - x86
  - x64

cache:
  - node_modules

build: off

before_test:
  - sc config sqlbrowser start= auto
  - net start sqlbrowser

test_script:
  - node --version
  - npm --version
  - cmd: |
      CALL %cd%\test\scripts\appveyor-runtests.cmd
      EXIT /B %errorlevel%
