version: "{build}"

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - IF "%nodejs_version%" == "10" (npm install msnodesqlv8@0.8.2) ELSE (npm install msnodesqlv8@0.6.12)

cache:
  - node_modules

build: off

before_test:
  - sc config sqlbrowser start= auto
  - net start sqlbrowser

test_script:
  - node --version
  - npm --version

  - cmd: |
      SET EXITVAL=0

      npm run-script test-unit || SET EXITVAL=1

      SET MSSQL_VERSION=2008
      powershell %cd%\test\scripts\appveyor.ps1 SQL2008R2SP2
      npm run-script test-tedious || SET EXITVAL=1
      npm run-script test-msnodesqlv8 || SET EXITVAL=1
      net stop MSSQL$SQL2008R2SP2

      SET MSSQL_VERSION=2012
      powershell %cd%\test\scripts\appveyor.ps1 SQL2012SP1
      npm run-script test-tedious || SET EXITVAL=1
      npm run-script test-msnodesqlv8 || SET EXITVAL=1
      net stop MSSQL$SQL2012SP1

      SET MSSQL_VERSION=2014
      powershell %cd%\test\scripts\appveyor.ps1 SQL2014
      npm run-script test-tedious || SET EXITVAL=1
      npm run-script test-msnodesqlv8 || SET EXITVAL=1
      net stop MSSQL$SQL2014

      SET MSSQL_VERSION=2016
      powershell %cd%\test\scripts\appveyor.ps1 SQL2016
      npm run-script test-tedious || SET EXITVAL=1
      npm run-script test-msnodesqlv8 || SET EXITVAL=1
      net stop MSSQL$SQL2016

      EXIT /B %EXITVAL%
