  version: '3'

services:
  toxiproxy:
    image: shopify/toxiproxy
    ports:
      - "8474:8474"
      - "21433:21433"
    links:
      - "mssql"

  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "31433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=S0meVeryHardPassword

  initmssqtestdb:
    image: microsoft/mssql-server-linux:2017-latest
    links:
      - mssql
    entrypoint: 
      - /opt/mssql-tools/bin/sqlcmd 
      - -S 
      - mssql 
      - -U 
      - sa 
      - -P 
      - S0meVeryHardPassword 
      - -d 
      - master
      - -Q 
      - "CREATE DATABASE mssql_test_db"